/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AddTodo: typeof import('./src/components/AddTodo.vue')['default']
    AppLayout: typeof import('./src/layouts/AppLayout.vue')['default']
    AuthLayout: typeof import('./src/layouts/AuthLayout.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IFeatherCheck: typeof import('~icons/feather/check')['default']
    IFeatherEdit: typeof import('~icons/feather/edit')['default']
    IFeatherTrash: typeof import('~icons/feather/trash')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TodoList: typeof import('./src/components/TodoList.vue')['default']
  }
}
